### ISSUE TITLE
Does graphviz even run on modern mac os x?

### ISSUE THREAD

**Issue by brandtdaniels** [vampirewalk/ObjectGraph-Xcode#11]
Does graphviz even run on modern mac os x? I don't see an El Capitan download for it...

**Comment by vampirewalk** [comment]
Yes, it works on my OS X El Capitan. If you are not sure which version works, just install it by 

```
$ brew install graphviz
```

If you haven't installed Homebrew, install it first.

```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

If you have any problem, welcome to reopen this issue.
Hope you enjoy. :smile:
